# escape=`
ARG BASE
FROM mcr.microsoft.com/windows/servercore:$BASE
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]
ARG AZP_TOKEN
ARG AZP_URL

WORKDIR /azp

RUN New-Item \"\azp\agent\" -ItemType directory | Out-Null; `
    Set-Location agent; `
    $base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(\":$env:AZP_TOKEN\")); `
    $url = \"$ENV:AZP_URL/_apis/distributedtask/packages/agent?platform=win-x64&`$top=1\"; `
    $package = Invoke-RestMethod -Headers @{Authorization=(\"Basic $base64AuthInfo\")} $url; `
    $packageUrl = $package[0].Value.downloadUrl; `
    Write-Host \"Downloading $packageUrl\"; `
    $wc = New-Object System.Net.WebClient; `
    $wc.DownloadFile($packageUrl, \"$(Get-Location)\agent.zip\"); `
    Expand-Archive -Path 'agent.zip' -DestinationPath '\azp\agent'


RUN iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')); `
    choco install -y docker-cli dotnetcore-sdk dotnet-5.0-sdk jq azure-cli; `
    choco install -y dotnet-sdk --pre; `
    Write-Host \"Installing nodejs\"; `
    choco install -y nodejs-lts; `
    Write-Host \"Installing windows-build-tools\"; `
    choco install -y python2 visualstudio2019-workload-vctools;

RUN Write-Host \"Installing npm packages\"; `
    npm install -g webpack vsce;

COPY start.ps1 .
CMD .\start.ps1
